# tasks/main.yml
---

- name: Create {{ etcd_user }} system group
  ansible.builtin.group:
    name: "{{ etcd_user }}"
    state: present
    system: yes

- name: Create {{ etcd_group }} user
  ansible.builtin.user:
    name: "{{ etcd_group }}"
    groups: etcd
    append: yes
    shell: /sbin/nologin
    state: present
    system: yes

- name: Prepare directories
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    mode: '0750'
  loop:
    - /etc/etcd
    - "{{ etcd_data_dir }}"

- name: Copy systemd template
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  notify: restart etcd service
