# tasks/main.yml
---


#- name: 123
#  debug:
#    var: "{% for host in groups['etcd'] %}{{ hostvars[host]['ansible_facts']['ansible_default_ipv4'] }} {% endfor %}"

#- name: setup
#  setup:

  #- name: 123
  #  debug:
  # var: "{% for host in groups['etcd'] %}{{ hostvars[host]['ansible_facts']['default_ipv4'] }} {% endfor %}"


    #- name: clear facts
    #meta: clear_facts

- name: install necessary packages
  apt:
    pkg:
      - iproute2
    state: latest
    update_cache: true

- name: collect facts
  setup:

- name: Display all variables/facts known for a host
  ansible.builtin.debug:
    var: ansible_facts
    #[ansible_facts][hostname]
      #verbosity: 4


- name: Create {{ etcd_user }} system group
  ansible.builtin.group:
    name: "{{ etcd_user }}"
    state: present
    system: yes

- name: Create {{ etcd_group }} user
  ansible.builtin.user:
    name: "{{ etcd_group }}"
    groups: etcd
    append: yes
    shell: /sbin/nologin
    state: present
    system: yes

- name: Prepare directories
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    mode: '0750'
  loop:
    - /etc/etcd
    - "{{ etcd_data_dir }}"

#- name: check ip
#  ansible.builtin.debug:
#    var: ansible_hostname
      
- name: add configuration envs
  with_items:
    - f: etcd.conf.yaml
      d: /etc/etcd
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    owner: '{{ etcd_user }}'
    group: '{{ etcd_group }}'
    mode: 0644
      
- name: Copy systemd template
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  notify: restart etcd service
