---
# tasks file for yml
- name: Create {{ etcd_group }} system group
  ansible.builtin.group:
    name: "{{ etcd_group }}"
    state: present
    system: yes
- name: Create {{ etcd_user }} user
  ansible.builtin.user:
    name: "{{ etcd_user }}"
    groups: etcd
    append: yes
    shell: /sbin/nologin
    state: present
    system: yes
- name: etcd etc directory creation
  file:
    state: directory
    path: /etc/etcd
- name: etcd /var/lib/ directory creation
  file:
    state: directory
    path: /var/lib/etcd
    owner: etcd
    group: etcd
- name: copy etcd unit file
  ansible.builtin.copy:
    src: etcd.service
    dest: /etc/systemd/system/etcd.service
