---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: matthewfeickert/docker-python3-ubuntu:3.10.5
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
