---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check user etcd exist
    ansible.builtin.user:
      name: etcd
      state: present
  - name: Check unit file exists
    stat:
      path: /etc/systemd/system/etcd.service
    register: unit_file_exists
  - name: "check if /file.txt exists"
    assert:
      that:
        - unit_file_exists.stat.exists == True
      success_msg: "unit file created"
      fail_msg: "unit file creation was not successful"
