---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  # read about systemd in containers:
  #   https://molecule.readthedocs.io/en/latest/examples.html#systemd-container
  - name: molecule_etcd-instance-01
    hostname: ubuntu
    # custom docker images with systemd for molecule
    #   https://github.com/marciopaiva/molecule-systemd-images
    image: mpaivabarbosa/molecule-systemd-ubuntu:20.04
    command: /sbin/init
    security_opts:
      - seccomp=path/to/seccomp.json
    # if you're using latest versions of ubuntu (22.04), check your default cgroup version.
    # command: stat -c %T -f /sys/fs/cgroup
    # if it is cgroup2fs, then change /etc/default/grub file, GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
    # update grub (sudo update-grub), reboot system to eplly changes
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    override_command: false
provisioner:
  name: ansible
#  # section below is used to set options in ansible.cfg
#  config_options:
#    defaults:
#      ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
