name: "ansible-etcd-cluster: tests"

on:
  push:
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

    - name: Set Up Git repository
      uses: actions/checkout@v3

    - name: Set Up Python 3.9
      uses: actions/setup-python@v2

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run tests
      run: |
        molecule test --all